"""initial catalog schema

Revision ID: 4ee67596e7e1
Revises: 
Create Date: 2026-10-01 14:06:08.682535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ee67596e7e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_asin', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('main_category', sa.String(length=255), nullable=True),
    sa.Column('store', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rating_number', sa.Integer(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('catalog_version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_version_id'], ['catalog_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_catalog_version_id'), 'products', ['catalog_version_id'], unique=False)
    op.create_index(op.f('ix_products_main_category'), 'products', ['main_category'], unique=False)
    op.create_index(op.f('ix_products_parent_asin'), 'products', ['parent_asin'], unique=True)
    op.create_index(op.f('ix_products_store'), 'products', ['store'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_store'), table_name='products')
    op.drop_index(op.f('ix_products_parent_asin'), table_name='products')
    op.drop_index(op.f('ix_products_main_category'), table_name='products')
    op.drop_index(op.f('ix_products_catalog_version_id'), table_name='products')
    op.drop_table('products')
    op.drop_table('catalog_versions')
    # ### end Alembic commands ###
